backend:
  name: git-gateway
  branch: main
collections:
  - name: pages
    label: pages
    folder: src/routes
    create: true
    fields:
      - name: title
      - name: nav_label
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - name: body
        widget: markdown
media_folder: "static/uploads"
public_folder: "/uploads"

show_preview_links: true

site_url: https://preview.artkidsfoundation.org
# display_url: https://preview.artkidsfoundation.org
logo_url: https://preview.artkidsfoundation.org/logo-512.png